{"uid":"2a3eeb05108d1229","name":"xml上传","fullName":"testsuites.uploadfile.test_upload_xml_test.TestCaseTestUploadXml#test_start","historyId":"f6e53193b072ef349df88e2cf0bb2404","time":{"start":1687689935910,"stop":1687689936248,"duration":338},"description":"TestCase ID: e626ce32-e749-4c86-9c68-50e03e9433d2","descriptionHtml":"<p>TestCase ID: e626ce32-e749-4c86-9c68-50e03e9433d2</p>\n","status":"broken","statusMessage":"httprunner.exceptions.ValidationFailure: assert body.message equal success(str)\t==> fail\ncheck_item: body.message\ncheck_value: 创建第1条标识: 88.408.13826286867/test001失败,原因: 标识【88.408.13826286867/test001】已存在;请修改后重新导入(str)\nassert_method: equal\nexpect_value: success(str)\nassert body.status equal 1(int)\t==> fail\ncheck_item: body.status\ncheck_value: -2(int)\nassert_method: equal\nexpect_value: 1(int)\nassert body.data equal True(bool)\t==> fail\ncheck_item: body.data\ncheck_value: False(bool)\nassert_method: equal\nexpect_value: True(bool)","statusTrace":"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:455: in test_start\n    return self.run_testcase(\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:357: in run_testcase\n    extract_mapping = self.__run_step(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:297: in __run_step\n    step_data = self.__run_step_testcase(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:251: in __run_step_testcase\n    .run()\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:384: in run\n    return self.run_testcase(testcase_obj)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:357: in run_testcase\n    extract_mapping = self.__run_step(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:295: in __run_step\n    step_data = self.__run_step_request(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:208: in __run_step_request\n    resp_obj.validate(\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/response.py:273: in validate\n    raise ValidationFailure(failures_string)\nE   httprunner.exceptions.ValidationFailure: assert body.message equal success(str)\t==> fail\nE   check_item: body.message\nE   check_value: 创建第1条标识: 88.408.13826286867/test001失败,原因: 标识【88.408.13826286867/test001】已存在;请修改后重新导入(str)\nE   assert_method: equal\nE   expect_value: success(str)\nE   assert body.status equal 1(int)\t==> fail\nE   check_item: body.status\nE   check_value: -2(int)\nE   assert_method: equal\nE   expect_value: 1(int)\nE   assert body.data equal True(bool)\t==> fail\nE   check_item: body.data\nE   check_value: False(bool)\nE   assert_method: equal\nE   expect_value: True(bool)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"TestCase ID: e626ce32-e749-4c86-9c68-50e03e9433d2","status":"broken","statusMessage":"httprunner.exceptions.ValidationFailure: assert body.message equal success(str)\t==> fail\ncheck_item: body.message\ncheck_value: 创建第1条标识: 88.408.13826286867/test001失败,原因: 标识【88.408.13826286867/test001】已存在;请修改后重新导入(str)\nassert_method: equal\nexpect_value: success(str)\nassert body.status equal 1(int)\t==> fail\ncheck_item: body.status\ncheck_value: -2(int)\nassert_method: equal\nexpect_value: 1(int)\nassert body.data equal True(bool)\t==> fail\ncheck_item: body.data\ncheck_value: False(bool)\nassert_method: equal\nexpect_value: True(bool)","statusTrace":"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:455: in test_start\n    return self.run_testcase(\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:357: in run_testcase\n    extract_mapping = self.__run_step(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:297: in __run_step\n    step_data = self.__run_step_testcase(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:251: in __run_step_testcase\n    .run()\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:384: in run\n    return self.run_testcase(testcase_obj)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:357: in run_testcase\n    extract_mapping = self.__run_step(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:295: in __run_step\n    step_data = self.__run_step_request(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:208: in __run_step_request\n    resp_obj.validate(\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/response.py:273: in validate\n    raise ValidationFailure(failures_string)\nE   httprunner.exceptions.ValidationFailure: assert body.message equal success(str)\t==> fail\nE   check_item: body.message\nE   check_value: 创建第1条标识: 88.408.13826286867/test001失败,原因: 标识【88.408.13826286867/test001】已存在;请修改后重新导入(str)\nE   assert_method: equal\nE   expect_value: success(str)\nE   assert body.status equal 1(int)\t==> fail\nE   check_item: body.status\nE   check_value: -2(int)\nE   assert_method: equal\nE   expect_value: 1(int)\nE   assert body.data equal True(bool)\t==> fail\nE   check_item: body.data\nE   check_value: False(bool)\nE   assert_method: equal\nE   expect_value: True(bool)","steps":[{"name":"step: 登录-企业","time":{"start":1687689935913,"stop":1687689936171,"duration":258},"status":"passed","steps":[{"name":"step: 登录-企业用户","time":{"start":1687689935913,"stop":1687689936171,"duration":258},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[],"parameters":[],"stepsCount":1,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},{"name":"step: 上传xml文件","time":{"start":1687689936172,"stop":1687689936248,"duration":76},"status":"broken","statusMessage":"httprunner.exceptions.ValidationFailure: assert body.message equal success(str)\t==> fail\ncheck_item: body.message\ncheck_value: 创建第1条标识: 88.408.13826286867/test001失败,原因: 标识【88.408.13826286867/test001】已存在;请修改后重新导入(str)\nassert_method: equal\nexpect_value: success(str)\nassert body.status equal 1(int)\t==> fail\ncheck_item: body.status\ncheck_value: -2(int)\nassert_method: equal\nexpect_value: 1(int)\nassert body.data equal True(bool)\t==> fail\ncheck_item: body.data\ncheck_value: False(bool)\nassert_method: equal\nexpect_value: True(bool)\n","statusTrace":"  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 357, in run_testcase\n    extract_mapping = self.__run_step(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 297, in __run_step\n    step_data = self.__run_step_testcase(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 251, in __run_step_testcase\n    .run()\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 384, in run\n    return self.run_testcase(testcase_obj)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 357, in run_testcase\n    extract_mapping = self.__run_step(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 295, in __run_step\n    step_data = self.__run_step_request(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 208, in __run_step_request\n    resp_obj.validate(\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/response.py\", line 273, in validate\n    raise ValidationFailure(failures_string)\n","steps":[{"name":"step: xml上传注册标识","time":{"start":1687689936172,"stop":1687689936247,"duration":75},"status":"broken","statusMessage":"httprunner.exceptions.ValidationFailure: assert body.message equal success(str)\t==> fail\ncheck_item: body.message\ncheck_value: 创建第1条标识: 88.408.13826286867/test001失败,原因: 标识【88.408.13826286867/test001】已存在;请修改后重新导入(str)\nassert_method: equal\nexpect_value: success(str)\nassert body.status equal 1(int)\t==> fail\ncheck_item: body.status\ncheck_value: -2(int)\nassert_method: equal\nexpect_value: 1(int)\nassert body.data equal True(bool)\t==> fail\ncheck_item: body.data\ncheck_value: False(bool)\nassert_method: equal\nexpect_value: True(bool)\n","statusTrace":"  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 357, in run_testcase\n    extract_mapping = self.__run_step(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 295, in __run_step\n    step_data = self.__run_step_request(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 208, in __run_step_request\n    resp_obj.validate(\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/response.py\", line 273, in validate\n    raise ValidationFailure(failures_string)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":1,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[{"uid":"1a7d30e85bd8c123","name":"stderr","source":"1a7d30e85bd8c123.txt","type":"text/plain","size":9912}],"parameters":[],"stepsCount":4,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"testsuites.uploadfile"},{"name":"suite","value":"test_upload_xml_test"},{"name":"subSuite","value":"TestCaseTestUploadXml"},{"name":"host","value":"shangjingjingdeMacBook-Pro.local"},{"name":"thread","value":"99475-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testsuites.uploadfile.test_upload_xml_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"2a3eeb05108d1229.json","parameterValues":[]}