2023-06-13 15:57:24.968 | INFO     | httprunner.runner:test_start:450 - Start to run testcase: 更新已审核通过的企业前缀用例集, TestCase ID: 244a8c7e-f6e5-4ccf-b389-d3111d4f0685
2023-06-13 15:58:39.975 | ERROR    | httprunner.parser:parse_string:342 - call function error:
func_name: get_session
args: ['3ecTeBOh971J5KRtcaEi7aFAf7vPRO9a', 'Yingzi125@@']
kwargs: {}
ConnectTimeout: HTTPConnectionPool(host='139.198.115.70', port=8000): Max retries exceeded with url: /api/home/test/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x104d074c0>, 'Connection to 139.198.115.70 timed out. (connect timeout=None)'))
