2023-06-13 15:56:08.828 | INFO     | httprunner.runner:test_start:450 - Start to run testcase: 企业注册信息暂存用例集, TestCase ID: f3138238-478b-4abb-a243-c82d57684e23
2023-06-13 15:57:23.832 | ERROR    | httprunner.parser:parse_string:342 - call function error:
func_name: get_session
args: ['ST9TalcTFC8fQKD2a743qHvECBUE9nRu', 'Yingzi125@@']
kwargs: {}
ConnectTimeout: HTTPConnectionPool(host='139.198.115.70', port=8000): Max retries exceeded with url: /api/home/test/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x107db4f70>, 'Connection to 139.198.115.70 timed out. (connect timeout=None)'))
